### ISSUE TITLE
I see the soneboard and shadowboard separately

### ISSUE THREAD

**Issue by toomasr** [online-go/goban#119]
Not sure what I'm doing wrong but I'm using quite simple code so I thought I'll ask here and maybe it is a bug.

I'm trying to use the library in my HTML page. I have the following code within my <script> tags. The board is drawn but I see the 2 canvases right after each other rather than overlayed. Am I doing anything wrong or how to go about it?

```
var goban_div = document.createElement("div");

const base_config = {
    interactive: true,
    mode: 'puzzle',
    board_div: goban_div,
    square_size: 30,
    draw_top_labels: true,
    draw_left_labels: true,
    draw_right_labels: true,
    draw_bottom_labels: true,
    bounds: {
        left: 0,
        right: 18,
        top: 0,
        bottom: 18,
    }
}

var goban = new window.Goban(base_config)
$("#goban_div").append(goban_div);
```

<img width="654" alt="Screenshot 2023-06-03 at 15 55 11" src="https://github.com/online-go/goban/assets/196499/40550bc7-70d7-45ab-a8cc-f34b5fe2b676">

**Comment by anoek** [comment]
It looks like you need the goban css loaded, see https://github.com/online-go/goban/blob/main/src/Goban.styl

**Comment by toomasr** [comment]
All solved now. I was not able to convert the styl to css with the tooling as supposedly didn't parse but I was able to hand craft it to css. Closing the issue, not a bug. Thank you for the quick reply!
