### ISSUE TITLE
Uploaded SGF "winner" text is wrong if SGF contains comments before "RE" (result) tag

### ISSUE THREAD

**Issue by JDNdeveloper** [online-go/goban#26]
Instead of showing "White/black wins by resignation" it only shows "White/black wins by". For example in this game: https://online-go.com/game/29322976

![image](https://user-images.githubusercontent.com/4645409/103600826-3763b980-4ebd-11eb-860f-cfa89ac68a97.png)

**Comment by anoek** [comment]
I transferred this to the goban repository as the related code is here I think: https://github.com/online-go/goban/blob/master/src/GoEngine.ts#L1794
