### ISSUE TITLE
[Dev tools] In VSCode, ESLint and Prettier plugins don't seem to work

### ISSUE THREAD

**Issue by benjaminpjones** [online-go/goban#55]
### Steps to reproduce

0) install and enable ESLint and prettier plugins
1) open Goban in VSCode.
2) create a lint/format error (an easy one is to change a `===` to a `==`)
3) Observe that there is no squiggly line

### Expected

See squiggly lines under lint errors and errors in the **Problems** pane.  For Prettier, I should be able to **Format on Save/Paste**, but it does not seem to work either.

This is an issue which I have tried to fix myself, but no luck.  I'm not sure if this is a VSCode issue, or a ESLint/Prettier/TS project config issue.  Hopefully someone with more know-how than I can resolve!

-----

### Workarounds

- `npm run checks` before a commit or push will run let you know if you have issues with either ESLint or Prettier (pending #54)
- `npm run prettier` will automatically format the project

**Comment by benjaminpjones** [comment]
I realized that Goban is on ESLint 8, while the react repo is on ESLint 7, so I tried installing v7, and lo and behold VSCode ESLint works again.  I'm not sure the solution is to downgrade, but wanted to update that I have a better idea about what the root problem is.

**Comment by benjaminpjones** [comment]
Figured out the missing piece!  I was running an old version of VSCode, which in turn was running an old version of node (v12.14).  ESLint 8 needs at least node v12.16 to run.  So if you ran into the same issue as me, try updating VSCode!

BTW, you can see what version of node is running either by going to "About VSCode" or by looking at the output panel, which is also where you'll see errors if ESLint is not loading:

<img width="1169" alt="Screen Shot 2022-01-29 at 11 00 29 PM" src="https://user-images.githubusercontent.com/25233703/151690096-63a876f4-fc0e-4da9-99de-014c3b3c0965.png">

**Comment by BHydden** [comment]
> try updating VSCode!

Why would you not have this set to auto-update?

**Comment by benjaminpjones** [comment]
So... funny story. If you forget to move VSCode from "Downloads" to "Applications", it can't update (manually or automatically) 😂

**Comment by BHydden** [comment]
Surprised you can run it out of Downloads 😅 Thought the "installer" always made you drag it over to Applications...

**Comment by benjaminpjones** [comment]
Yeah I dunno how that all works, but it does 😅

![63a6b5.jpg](https://user-images.githubusercontent.com/25233703/151712083-a36997f6-7cbe-4b8e-9a14-7628fdaa513e.jpg)

**Comment by BHydden** [comment]
1337
